version: "3.3"
services:
  it-tools:
    container_name: it-tools_internal
    restart: unless-stopped
    expose:
      - "8080"
    image: ghcr.io/corentinth/it-tools:latest
networks:
  default:
    name: $DOCKER_INTERNAL_NETWORK
    external: true