include:
  - ../compose-common.yml

services:
  actual_server:
    container_name: actual_internal
    image: docker.io/actualbudget/actual-server:latest
#    env_file: .env
    ports:
      - '5006:5006'
    volumes:
      - ./actual-data:/data
    restart: unless-stopped
    networks:
      - dmz-net